version: '3.8'

services:
  application_image:
    image: vprofile-app:latest
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    volumes:
      - myvolume1:/sandhya
    networks:
      - network1
    depends_on:
      - database_image

  database_image:
    image: vprofile-db:latest
    ports:
      - "1112:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devopspassword
      MYSQL_DATABASE: accounts
    deploy:
      replicas: 1
    volumes:
      - myvolume2:/sandhyaSrinivas
    networks:
      - network1

volumes:
  myvolume1:
  myvolume2:

networks:
  network1:
    driver: overlay
